// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface AnnouncementBar {
  text: string;
  cta?: Cta[];
  croct?: unknown;
  component: "announcement-bar";
  _uid: string;
  [k: string]: unknown;
}

export interface Catalog {
  category: number | string;
  component: "catalog";
  _uid: string;
  [k: string]: unknown;
}

export interface CheckoutCallout {
  icon: StoryblokAsset;
  title: string;
  text: string;
  croct?: unknown;
  component: "checkout-callout";
  _uid: string;
  [k: string]: unknown;
}

export interface Cta {
  label: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "cta";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  headline: string;
  tagline: string;
  cta: Cta[];
  image: StoryblokAsset;
  croct?: unknown;
  component: "hero-section";
  _uid: string;
  [k: string]: unknown;
}

export interface Note {
  content: string;
  component: "note";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (AnnouncementBar | Catalog | CheckoutCallout | HeroSection)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Product {
  image: StoryblokAsset;
  price: string;
  category: number | string;
  tagline: string;
  description: string;
  component: "product";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Page | Product;
