/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

/**
 * Coupon list
 *
 * A list of coupons.
 */
type Def$06121f1f = {
    /**
   * Coupons
   */
    coupons: Array<{
    /**
     * Code
     *
     * The coupon code.
     */
        code: string,
        /**
     * Rule
     *
     * The eligibility condition for the coupon.
     */
        rule: string,
        /**
     * Title
     *
     * Display name shown after the coupon is applied.
     */
        title: string,
        /**
     * Discount
     *
     * Percentage discount from 0% to 100%.
     */
        discount?: number,
        /**
     * Eligible
     *
     * Whether the current user is eligible for this coupon.
     */
        eligible: boolean,
        /**
     * Max discount
     *
     * Maximum discount as an absolute monetary value. Omit for no cap
     */
        maxDiscount?: number,
        /**
     * Free shipping
     *
     * Whether the coupon waives the shipping fee.
     */
        freeShipping: boolean,
    }>,
};

declare module '@croct/plug/slot' {
    type CouponsV3 = Def$06121f1f & {_component: 'coupon-list@3' | null};

    export interface VersionedSlotMap {
        coupons: {
            latest: CouponsV3,
            '3': CouponsV3,
        };
    }
}

export {};
